### ISSUE TITLE
GitHub resource didn't resolve

### ISSUE THREAD

**Issue by jasperblues** [lju-lazarevic/wine#1]
Excellent data set and series, thank you!

Load query as shown in README doesn't work (anymore?). 

Errors with: Couldn't load the external resource at: https://github.com/lju-lazarevic/importdata/blob/master/winemag-data-130k-v3.csv?raw=true

```cypher
:auto //add this line if you're using Neo4j Browser
USING PERIODIC COMMIT 1000
LOAD CSV WITH HEADERS FROM 'https://raw.githubusercontent.com/lju-lazarevic/wine/master/data/winemag-data-130k-v3.csv' AS row
 //etc 
```

^-- Using with this URL works for me. 

Also is it intentional to spell 'PROVINCE' in the diagram as 'PROVENCE' ?

**Comment by jasperblues** [comment]
Also, using default memory settings above query OOM'd, however setting to pageCache and HEAP of 6g each respectively, it worked just fine. Perhaps mention in README?

^--- *Edit:* Oops sorry. This was because I applied the indexes to the wrong database.

**Comment by lju-lazarevic** [comment]
Hi Jasper,

Glad to hear you're enjoying the series :)

Great catch on the LOAD CSV - I've fixed that now. Thank you!
